name = "MCAnalyzer"
uuid = "a81df072-f4bb-11e8-03d3-cfaeda626d18"
authors = ["Valentin Churavy <v.churavy@gmail.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
LLVM = "929cbde3-209d-540e-8aea-75f648917ca0"

[compat]
julia = "1.3"
