name = "MCAnalyzer"
uuid = "a81df072-f4bb-11e8-03d3-cfaeda626d18"
authors = ["Valentin Churavy <v.churavy@gmail.com>"]
version = "0.2.0"

[deps]
GPUCompiler = "61eb1bfa-7361-4325-ad38-22787b887f55"
LLVM = "929cbde3-209d-540e-8aea-75f648917ca0"

[compat]
GPUCompiler = "0.7, 0.8"
LLVM = "1.3, 2, 3"
julia = "1.3"
