name = "MCAnalyzer"
uuid = "a81df072-f4bb-11e8-03d3-cfaeda626d18"
authors = ["Valentin Churavy <v.churavy@gmail.com>"]
version = "0.1.0"

[deps]
LLVM = "929cbde3-209d-540e-8aea-75f648917ca0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[targets]
test = ["Test", "LinearAlgebra"]
